///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the ROXParser
// at 3/6/2017 9:08:54 PM

#ifndef __ROXMEASUREMENTS_H
#define __ROXMEASUREMENTS_H

/*****************************************************************************/
/* Packet types                                                              */
/*****************************************************************************/
#define roxPT_UltrasonicDistance 1
#define roxPT_AirTemperature 2

/*****************************************************************************/
/* Packets                                                                   */
/*****************************************************************************/

///////////////////////////////////////////////////////////////////////////////
// UltrasonicDistance
typedef struct
{
  PacketHeader header;

  uint16_t Distance1;
  uint16_t Distance2;
  uint16_t Distance3;
  uint16_t Distance4;
} roxUltrasonicDistance;

///////////////////////////////////////////////////////////////////////////////
// AirTemperature
typedef struct
{
  PacketHeader header;

  uint16_t TemperatureADC;
  uint16_t Temperature;
} roxAirTemperature;


#endif

